// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA5hM5cGkGfXt-iXIhlqEkzrKgxMG5m90',
    appId: '1:377173847601:web:64e8fe7adae30250d62f10',
    messagingSenderId: '377173847601',
    projectId: 'appbook-e5b85',
    authDomain: 'appbook-e5b85.firebaseapp.com',
    storageBucket: 'appbook-e5b85.firebasestorage.app',
    measurementId: 'G-JTJ97432P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJZsdoaZO7ac9DSDuoQrNtVXSTpHUduw',
    appId: '1:377173847601:android:73413867054be1f4d62f10',
    messagingSenderId: '377173847601',
    projectId: 'appbook-e5b85',
    storageBucket: 'appbook-e5b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZJ9T-EC78e4HsUcmVzhMxWHj4HZSp_M',
    appId: '1:377173847601:ios:e880c7d8a0507cbdd62f10',
    messagingSenderId: '377173847601',
    projectId: 'appbook-e5b85',
    storageBucket: 'appbook-e5b85.firebasestorage.app',
    iosBundleId: 'com.example.appbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ZJ9T-EC78e4HsUcmVzhMxWHj4HZSp_M',
    appId: '1:377173847601:ios:e880c7d8a0507cbdd62f10',
    messagingSenderId: '377173847601',
    projectId: 'appbook-e5b85',
    storageBucket: 'appbook-e5b85.firebasestorage.app',
    iosBundleId: 'com.example.appbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA5hM5cGkGfXt-iXIhlqEkzrKgxMG5m90',
    appId: '1:377173847601:web:a1c7b5ba06cfc743d62f10',
    messagingSenderId: '377173847601',
    projectId: 'appbook-e5b85',
    authDomain: 'appbook-e5b85.firebaseapp.com',
    storageBucket: 'appbook-e5b85.firebasestorage.app',
    measurementId: 'G-L1SR9NM6MW',
  );
}
